### ISSUE TITLE
i have no sound

### ISSUE THREAD

**Issue by therealfunniman** [isledecomp/SIEdit#16]
when i try to listen to wave files contained in any si file, it will play but i wont hear anything
I have multiple audio devices and the default one is my headphones so i have no idea
im sorry for the lack of info but i dont have a clue whats wrong so i cant really give instructions to reproduce it

i know rebuilder net wont be updated but the same thing happens with that too
just thought id mention that

**Comment by itsmattkc** [comment]
Rebuilder uses a completely different sound system to SIEdit. The two codebases are completely unrelated. This suggests it's most likely something on your end.

Regardless, there was a sound issue with the latest master on Windows (not the release build), so if you compiled from source you may have encountered that. That was fixed in 04dc68a7e9df0a45180c37b33da388d27da54704 so either way I'm going to mark this resolved for now.
